# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquot_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time aliquot created')),
                ('is_primary', models.BooleanField(default=False, editable=False)),
                ('count', models.IntegerField(editable=False, help_text='pos in sequence of aliquots from parent')),
                ('medium', models.CharField(choices=[('tube_any', 'Tube'), ('tube_edta', 'Tube EDTA'), ('swab', 'Swab'), ('dbs_card', 'DBS Card')], default='TUBE', max_length=25, verbose_name='Medium')),
                ('medium_count', models.IntegerField(default=1, editable=False, help_text='e.g. number of tubes')),
                ('original_measure', models.DecimalField(decimal_places=2, default='5.00', max_digits=10)),
                ('current_measure', models.DecimalField(decimal_places=2, default='5.00', max_digits=10)),
                ('measure_units', models.CharField(choices=[('mL', 'mL'), ('uL', 'uL'), ('spots', 'spots'), ('n/a', 'Not Applicable')], default='mL', max_length=25)),
                ('status', models.CharField(choices=[('available', 'available'), ('consumed', 'consumed')], default='available', max_length=25)),
                ('condition', models.CharField(choices=[('10', 'OK'), ('20', 'Inadequate volume for testing'), ('30', 'Clotted or haemolised'), ('40', 'Wrong tube type, unable to test'), ('50', 'Sample degradation has occured. Unsuitable for testing'), ('60', 'Expired tube'), ('70', 'Technical problem at lab, unable to test')], default='10', max_length=25)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_identifier', models.CharField(editable=False, max_length=25, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('box_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('testing', 'Testing'), ('storage', 'Storage'), ('other', 'Other')], default='testing', max_length=25)),
                ('status', models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('packed', 'Packed'), ('shipped', 'Shipped')], default='open', max_length=15)),
                ('accept_primary', models.BooleanField(default=False, help_text="Tick to allow 'primary' specimens to be added to this box")),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('identifier', models.CharField(max_length=25)),
                ('comment', models.CharField(blank=True, max_length=25, null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Box')),
            ],
        ),
    ]
